services:
  backend:
    build:
      context: ./app/backend
    env_file:
      - ./app/backend/.env
    ports:
      - "8080:8080"
    command: sh -c "npm i && npm run dev"

  frontend:
    build:
      context: ./app/frontend
    env_file:
      - ./app/frontend/.env
    ports:
      - "5173:5173"
    command: sh -c "npm i && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend
